# Generated by Django 6.0.1 on 2026-01-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regalos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('imagen', models.URLField()),
                ('descripcion', models.TextField()),
                ('url', models.URLField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('categoria', models.CharField(choices=[('G', 'Gifts'), ('D', 'Dates'), ('T', 'Travels')])),
            ],
        ),
    ]
