# Generated by Django 6.0.1 on 2026-01-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regalos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regalos',
            old_name='precio',
            new_name='costo',
        ),
        migrations.RenameField(
            model_name='regalos',
            old_name='url',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='regalos',
            old_name='nombre',
            new_name='name',
        ),
        migrations.AddField(
            model_name='regalos',
            name='comprado',
            field=models.BooleanField(default=False),
        ),
    ]
